<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\scrcpy-launcher.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScrcpyLauncher.Core\ScrcpyLauncher.Core.csproj" />
    <ProjectReference Include="..\ScrcpyLauncher.Infrastructure\ScrcpyLauncher.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\scrcpy-launcher.ico" />
  </ItemGroup>

</Project>
